-- SUPRIR Educação V5.2.0
-- Controle de estoque: entradas, saídas automáticas e visibilidade por perfil.

begin;

-- -----------------------------------------------------------------------------
-- 1. Saldo físico atual por material
-- -----------------------------------------------------------------------------

alter table public.materials
  add column if not exists stock_quantity numeric(14,2) not null default 0;

alter table public.materials
  add column if not exists stock_updated_at timestamptz;

update public.materials
set stock_quantity = greatest(coalesce(stock_quantity, 0), 0)
where stock_quantity is null or stock_quantity < 0;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'materials_stock_quantity_check'
      and conrelid = 'public.materials'::regclass
  ) then
    alter table public.materials
      add constraint materials_stock_quantity_check
      check (stock_quantity >= 0);
  end if;
end $$;

create index if not exists materials_stock_idx
  on public.materials (ativo, stock_quantity, nome);

-- -----------------------------------------------------------------------------
-- 2. Livro razão do estoque
-- -----------------------------------------------------------------------------

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  material_id uuid not null references public.materials(id) on delete restrict,
  movement_type text not null,
  quantity numeric(14,2) not null check (quantity > 0),
  balance_before numeric(14,2) not null check (balance_before >= 0),
  balance_after numeric(14,2) not null check (balance_after >= 0),
  document_number text,
  notes text,
  request_id uuid references public.requests(id) on delete set null,
  delivery_id uuid references public.deliveries(id) on delete set null,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text,
  actor_email text,
  created_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'inventory_movements_type_check'
      and conrelid = 'public.inventory_movements'::regclass
  ) then
    alter table public.inventory_movements
      add constraint inventory_movements_type_check
      check (movement_type in ('entry', 'dispatch'));
  end if;
end $$;

create index if not exists inventory_movements_material_created_idx
  on public.inventory_movements (material_id, created_at desc);
create index if not exists inventory_movements_request_idx
  on public.inventory_movements (request_id, created_at desc);
create index if not exists inventory_movements_delivery_idx
  on public.inventory_movements (delivery_id, created_at desc);

alter table public.inventory_movements enable row level security;

drop policy if exists inventory_movements_select_internal on public.inventory_movements;
create policy inventory_movements_select_internal
on public.inventory_movements for select to authenticated
using (public.can_view_network_operations(auth.uid()));

-- Movimentações são gravadas exclusivamente pelas RPCs security definer.
revoke all on table public.inventory_movements from anon, authenticated;
grant select on table public.inventory_movements to authenticated;

-- -----------------------------------------------------------------------------
-- 3. Catálogo por perfil
--    Escola: somente material ativo e com saldo > 0.
--    SME/Almoxarifado/Admin: catálogo completo e saldo atual.
-- -----------------------------------------------------------------------------

drop policy if exists materials_select_scoped_v5 on public.materials;
drop policy if exists materials_select_stock_scoped_v52 on public.materials;
create policy materials_select_stock_scoped_v52
on public.materials for select to authenticated
using (
  public.is_active_user(auth.uid())
  and (
    (
      public.current_school_id(auth.uid()) is not null
      and ativo = true
      and stock_quantity > 0
    )
    or public.can_view_network_operations(auth.uid())
  )
);

-- O almoxarifado passa a poder manter o catálogo; estoque não é alterado
-- diretamente por INSERT/UPDATE, somente pelas RPCs abaixo.
drop policy if exists materials_insert_system_admin on public.materials;
drop policy if exists materials_update_system_admin on public.materials;
drop policy if exists materials_insert_warehouse_v52 on public.materials;
drop policy if exists materials_update_warehouse_v52 on public.materials;

create policy materials_insert_warehouse_v52
on public.materials for insert to authenticated
with check (public.can_operate_warehouse(auth.uid()));

create policy materials_update_warehouse_v52
on public.materials for update to authenticated
using (public.can_operate_warehouse(auth.uid()))
with check (public.can_operate_warehouse(auth.uid()));

-- Restringe a alteração direta das colunas de saldo.
revoke all on table public.materials from anon, authenticated;
grant select on table public.materials to authenticated;
grant delete on table public.materials to authenticated;

-- -----------------------------------------------------------------------------
-- 4. Entrada de estoque
-- -----------------------------------------------------------------------------

create or replace function public.register_stock_entry(
  p_material_id uuid,
  p_quantity numeric,
  p_document_number text default null,
  p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_material public.materials%rowtype;
  v_profile public.profiles%rowtype;
  v_before numeric(14,2);
  v_after numeric(14,2);
  v_movement_id bigint;
begin
  if not public.can_operate_warehouse(auth.uid()) then
    raise exception 'Seu perfil não possui permissão para registrar entradas de estoque.';
  end if;

  if p_material_id is null then
    raise exception 'Selecione o material.';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'A quantidade de entrada deve ser maior que zero.';
  end if;

  select * into v_profile
  from public.profiles
  where id = auth.uid();

  select * into v_material
  from public.materials
  where id = p_material_id
  for update;

  if v_material.id is null then
    raise exception 'Material não encontrado.';
  end if;

  v_before := coalesce(v_material.stock_quantity, 0);
  v_after := v_before + p_quantity;

  update public.materials
  set stock_quantity = v_after,
      stock_updated_at = now()
  where id = p_material_id;

  insert into public.inventory_movements (
    material_id, movement_type, quantity,
    balance_before, balance_after,
    document_number, notes,
    actor_id, actor_name, actor_email
  ) values (
    p_material_id, 'entry', p_quantity,
    v_before, v_after,
    nullif(btrim(coalesce(p_document_number, '')), ''),
    nullif(btrim(coalesce(p_notes, '')), ''),
    auth.uid(), v_profile.full_name, v_profile.email
  )
  returning id into v_movement_id;

  return v_movement_id;
end;
$$;

revoke all on function public.register_stock_entry(uuid, numeric, text, text)
  from public, anon, authenticated;
grant execute on function public.register_stock_entry(uuid, numeric, text, text)
  to authenticated;

-- Cadastro/edição de material pelo almoxarifado, com estoque inicial auditado.
create or replace function public.save_warehouse_material(
  p_material_id uuid,
  p_nome text,
  p_codigo text,
  p_categoria text,
  p_unidade text,
  p_quantidade_minima numeric,
  p_descricao text,
  p_ativo boolean,
  p_initial_stock numeric default 0
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_material_id uuid;
  v_initial numeric(14,2) := greatest(coalesce(p_initial_stock, 0), 0);
begin
  if not public.can_operate_warehouse(auth.uid()) then
    raise exception 'Seu perfil não possui permissão para cadastrar ou editar materiais.';
  end if;

  if nullif(btrim(coalesce(p_nome, '')), '') is null then
    raise exception 'Informe o nome do material.';
  end if;
  if nullif(btrim(coalesce(p_unidade, '')), '') is null then
    raise exception 'Informe a unidade de medida.';
  end if;
  if p_quantidade_minima is not null and p_quantidade_minima < 0 then
    raise exception 'A quantidade mínima não pode ser negativa.';
  end if;

  if p_material_id is null then
    insert into public.materials (
      nome, codigo, categoria, unidade, quantidade_minima, descricao, ativo, created_by
    ) values (
      btrim(p_nome), nullif(btrim(coalesce(p_codigo, '')), ''),
      nullif(btrim(coalesce(p_categoria, '')), ''), btrim(p_unidade),
      p_quantidade_minima, nullif(btrim(coalesce(p_descricao, '')), ''),
      coalesce(p_ativo, true), auth.uid()
    ) returning id into v_material_id;

    if v_initial > 0 then
      perform public.register_stock_entry(
        v_material_id,
        v_initial,
        null,
        'Estoque inicial cadastrado junto com o material.'
      );
    end if;
  else
    update public.materials
    set nome = btrim(p_nome),
        codigo = nullif(btrim(coalesce(p_codigo, '')), ''),
        categoria = nullif(btrim(coalesce(p_categoria, '')), ''),
        unidade = btrim(p_unidade),
        quantidade_minima = p_quantidade_minima,
        descricao = nullif(btrim(coalesce(p_descricao, '')), ''),
        ativo = coalesce(p_ativo, true)
    where id = p_material_id
    returning id into v_material_id;

    if v_material_id is null then
      raise exception 'Material não encontrado.';
    end if;
  end if;

  return v_material_id;
end;
$$;

revoke all on function public.save_warehouse_material(uuid, text, text, text, text, numeric, text, boolean, numeric)
  from public, anon, authenticated;
grant execute on function public.save_warehouse_material(uuid, text, text, text, text, numeric, text, boolean, numeric)
  to authenticated;

-- -----------------------------------------------------------------------------
-- 5. Pedido da escola: valida o saldo atual
-- -----------------------------------------------------------------------------

create or replace function public.save_school_request(
  p_request_id uuid,
  p_priority text,
  p_purpose text,
  p_requested_delivery_date date,
  p_notes text,
  p_school_contact_name text,
  p_school_contact_phone text,
  p_items jsonb,
  p_submit boolean
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_request public.requests%rowtype;
  v_item record;
  v_material public.materials%rowtype;
  v_request_id uuid;
begin
  select * into v_profile from public.profiles where id = auth.uid();

  if v_profile.id is null or not v_profile.active or v_profile.account_type <> 'school' or v_profile.school_id is null then
    raise exception 'Seu usuário não está vinculado a uma escola ativa.';
  end if;

  if p_priority not in ('low', 'normal', 'high', 'urgent') then
    raise exception 'Prioridade inválida.';
  end if;

  if nullif(btrim(coalesce(p_purpose, '')), '') is null then
    raise exception 'Informe a finalidade do pedido.';
  end if;

  if p_requested_delivery_date is not null and p_requested_delivery_date < current_date then
    raise exception 'A data desejada não pode ser anterior à data atual.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Adicione pelo menos um material ao pedido.';
  end if;

  if p_request_id is null then
    insert into public.requests (
      school_id, status, priority, purpose, requested_delivery_date, notes,
      school_contact_name, school_contact_phone,
      created_by, created_by_name, created_by_email
    ) values (
      v_profile.school_id, 'draft', p_priority, btrim(p_purpose), p_requested_delivery_date, nullif(btrim(p_notes), ''),
      nullif(btrim(p_school_contact_name), ''), nullif(btrim(p_school_contact_phone), ''),
      auth.uid(), v_profile.full_name, v_profile.email
    ) returning * into v_request;
  else
    select * into v_request
    from public.requests
    where id = p_request_id
    for update;

    if v_request.id is null or v_request.school_id <> v_profile.school_id then
      raise exception 'Pedido não encontrado para esta escola.';
    end if;

    if v_request.status <> 'draft' then
      raise exception 'Somente pedidos em rascunho podem ser alterados.';
    end if;

    update public.requests set
      priority = p_priority,
      purpose = btrim(p_purpose),
      requested_delivery_date = p_requested_delivery_date,
      notes = nullif(btrim(p_notes), ''),
      school_contact_name = nullif(btrim(p_school_contact_name), ''),
      school_contact_phone = nullif(btrim(p_school_contact_phone), '')
    where id = v_request.id
    returning * into v_request;

    delete from public.request_items where request_id = v_request.id;
  end if;

  for v_item in
    select * from jsonb_to_recordset(p_items)
      as x(material_id uuid, quantity numeric, notes text)
  loop
    if v_item.material_id is null or v_item.quantity is null or v_item.quantity <= 0 then
      raise exception 'Existe um item com material ou quantidade inválida.';
    end if;

    select * into v_material
    from public.materials
    where id = v_item.material_id and ativo = true;

    if v_material.id is null then
      raise exception 'Um dos materiais não existe ou está inativo.';
    end if;

    if coalesce(v_material.stock_quantity, 0) <= 0 then
      raise exception 'O material % está sem estoque no momento.', v_material.nome;
    end if;

    if v_item.quantity > v_material.stock_quantity then
      raise exception 'A quantidade solicitada de % ultrapassa o estoque disponível (% %).',
        v_material.nome, v_material.stock_quantity, v_material.unidade;
    end if;

    insert into public.request_items (
      request_id, material_id, requested_quantity, approved_quantity,
      material_name_snapshot, unit_snapshot, school_notes
    ) values (
      v_request.id, v_material.id, v_item.quantity, 0,
      v_material.nome, v_material.unidade, nullif(btrim(v_item.notes), '')
    );
  end loop;

  v_request_id := v_request.id;

  if coalesce(p_submit, false) then
    update public.requests
    set status = 'submitted', submitted_at = now()
    where id = v_request_id;

    perform public.log_request_event(
      v_request_id,
      'request_submitted',
      'draft',
      'submitted',
      'Pedido enviado pela escola para análise da SME.'
    );
  elsif p_request_id is null then
    perform public.log_request_event(
      v_request_id,
      'draft_created',
      null,
      'draft',
      'Rascunho do pedido criado pela escola.'
    );
  else
    perform public.log_request_event(
      v_request_id,
      'draft_updated',
      'draft',
      'draft',
      'Rascunho do pedido atualizado pela escola.'
    );
  end if;

  return v_request_id;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. Autorização da SME: mostra/valida o saldo físico existente
-- -----------------------------------------------------------------------------

create or replace function public.authorize_request(
  p_request_id uuid,
  p_items jsonb,
  p_authorization_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.requests%rowtype;
  v_profile public.profiles%rowtype;
  v_item record;
  v_request_item public.request_items%rowtype;
  v_stock numeric(14,2);
  v_positive_count integer := 0;
  v_old_status text;
begin
  if not public.can_authorize_requests(auth.uid()) then
    raise exception 'Seu perfil não possui permissão para autorizar pedidos.';
  end if;

  select * into v_profile from public.profiles where id = auth.uid();
  select * into v_request from public.requests where id = p_request_id for update;

  if v_request.id is null then raise exception 'Pedido não encontrado.'; end if;
  if v_request.status not in ('submitted', 'under_review') then
    raise exception 'O pedido não está disponível para autorização.';
  end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception 'Informe as quantidades autorizadas.';
  end if;

  v_old_status := v_request.status;

  update public.request_items
  set approved_quantity = 0, sme_notes = null
  where request_id = p_request_id;

  for v_item in
    select * from jsonb_to_recordset(p_items)
      as x(request_item_id uuid, approved_quantity numeric, notes text)
  loop
    select * into v_request_item
    from public.request_items
    where id = v_item.request_item_id and request_id = p_request_id
    for update;

    if v_request_item.id is null then
      raise exception 'Um dos itens informados não pertence ao pedido.';
    end if;
    if v_item.approved_quantity is null or v_item.approved_quantity < 0
       or v_item.approved_quantity > v_request_item.requested_quantity then
      raise exception 'Quantidade autorizada inválida para o material %.', v_request_item.material_name_snapshot;
    end if;

    select coalesce(stock_quantity, 0)
    into v_stock
    from public.materials
    where id = v_request_item.material_id;

    if v_item.approved_quantity > coalesce(v_stock, 0) then
      raise exception 'A quantidade autorizada de % ultrapassa o estoque atual (% %).',
        v_request_item.material_name_snapshot, coalesce(v_stock, 0), v_request_item.unit_snapshot;
    end if;

    update public.request_items set
      approved_quantity = v_item.approved_quantity,
      sme_notes = nullif(btrim(v_item.notes), '')
    where id = v_request_item.id;
  end loop;

  select count(*) into v_positive_count
  from public.request_items
  where request_id = p_request_id and approved_quantity > 0;

  if v_positive_count = 0 then
    raise exception 'Autorize ao menos um item ou rejeite o pedido.';
  end if;

  update public.requests set
    status = 'approved',
    received_by = coalesce(received_by, auth.uid()),
    received_by_name = coalesce(received_by_name, v_profile.full_name),
    received_by_email = coalesce(received_by_email, v_profile.email),
    received_at = coalesce(received_at, now()),
    authorized_by = auth.uid(),
    authorized_by_name = v_profile.full_name,
    authorized_by_email = v_profile.email,
    authorized_at = now(),
    authorization_notes = nullif(btrim(p_authorization_notes), ''),
    rejected_by = null,
    rejected_by_name = null,
    rejected_at = null,
    rejection_reason = null
  where id = p_request_id;

  perform public.log_request_event(
    p_request_id, 'request_authorized', v_old_status, 'approved',
    'Pedido autorizado pela SME e liberado para o almoxarifado.'
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- 7. Expedição: baixa física do estoque de forma atômica
-- -----------------------------------------------------------------------------

create or replace function public.register_dispatch(
  p_request_id uuid,
  p_dispatch_date date,
  p_document_number text,
  p_observations text,
  p_items jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.requests%rowtype;
  v_profile public.profiles%rowtype;
  v_delivery_id uuid;
  v_item record;
  v_request_item public.request_items%rowtype;
  v_already_dispatched numeric;
  v_stock_before numeric(14,2);
  v_stock_after numeric(14,2);
  v_item_count integer := 0;
begin
  if not public.can_operate_warehouse(auth.uid()) then
    raise exception 'Seu perfil não possui permissão para registrar remessas.';
  end if;

  if p_dispatch_date is null then raise exception 'Informe a data da saída.'; end if;
  if p_dispatch_date > current_date then raise exception 'A data da saída não pode estar no futuro.'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Adicione ao menos um item à remessa.';
  end if;

  select * into v_profile from public.profiles where id = auth.uid();
  select * into v_request from public.requests where id = p_request_id for update;

  if v_request.id is null then raise exception 'Pedido não encontrado.'; end if;
  if v_request.status not in ('approved', 'preparing', 'partially_delivered') then
    raise exception 'O pedido não está disponível para expedição.';
  end if;

  insert into public.deliveries (
    request_id, school_id, status, dispatch_date, delivery_date,
    document_number, delivered_by_name, delivered_by_department,
    observations, registered_by, registered_by_email, registered_by_name
  ) values (
    p_request_id, v_request.school_id, 'dispatched', p_dispatch_date, p_dispatch_date,
    nullif(btrim(p_document_number), ''),
    coalesce(v_profile.full_name, v_profile.email, 'Almoxarifado'),
    coalesce(nullif(btrim(v_profile.position), ''), 'Almoxarifado'),
    nullif(btrim(p_observations), ''),
    auth.uid(), v_profile.email, v_profile.full_name
  ) returning id into v_delivery_id;

  for v_item in
    select * from jsonb_to_recordset(p_items)
      as x(request_item_id uuid, quantity numeric, notes text)
  loop
    select * into v_request_item
    from public.request_items
    where id = v_item.request_item_id and request_id = p_request_id
    for update;

    if v_request_item.id is null then raise exception 'Um dos itens não pertence ao pedido.'; end if;
    if v_item.quantity is null or v_item.quantity <= 0 then raise exception 'Quantidade de remessa inválida.'; end if;

    select coalesce(sum(di.quantity), 0)
    into v_already_dispatched
    from public.delivery_items di
    join public.deliveries d on d.id = di.delivery_id
    where di.request_item_id = v_request_item.id
      and d.status in ('dispatched', 'delivered');

    if v_item.quantity > (v_request_item.approved_quantity - v_already_dispatched) then
      raise exception 'A quantidade do material % ultrapassa o saldo autorizado.', v_request_item.material_name_snapshot;
    end if;

    select stock_quantity
    into v_stock_before
    from public.materials
    where id = v_request_item.material_id
    for update;

    if v_stock_before is null then
      raise exception 'Material % não encontrado no estoque.', v_request_item.material_name_snapshot;
    end if;

    if v_item.quantity > v_stock_before then
      raise exception 'Estoque insuficiente para %. Disponível: % %.',
        v_request_item.material_name_snapshot, v_stock_before, v_request_item.unit_snapshot;
    end if;

    v_stock_after := v_stock_before - v_item.quantity;

    update public.materials
    set stock_quantity = v_stock_after,
        stock_updated_at = now()
    where id = v_request_item.material_id;

    insert into public.delivery_items (
      delivery_id, request_item_id, material_id, quantity,
      unit_snapshot, material_name_snapshot, notes
    ) values (
      v_delivery_id, v_request_item.id, v_request_item.material_id, v_item.quantity,
      v_request_item.unit_snapshot, v_request_item.material_name_snapshot,
      nullif(btrim(v_item.notes), '')
    );

    insert into public.inventory_movements (
      material_id, movement_type, quantity,
      balance_before, balance_after,
      document_number, notes,
      request_id, delivery_id,
      actor_id, actor_name, actor_email
    ) values (
      v_request_item.material_id, 'dispatch', v_item.quantity,
      v_stock_before, v_stock_after,
      nullif(btrim(coalesce(p_document_number, '')), ''),
      nullif(btrim(coalesce(v_item.notes, p_observations, '')), ''),
      p_request_id, v_delivery_id,
      auth.uid(), v_profile.full_name, v_profile.email
    );

    v_item_count := v_item_count + 1;
  end loop;

  if v_item_count = 0 then raise exception 'Nenhum item válido foi informado.'; end if;

  update public.requests set status = 'dispatched' where id = p_request_id;

  perform public.log_request_event(
    p_request_id,
    'delivery_dispatched',
    v_request.status,
    'dispatched',
    'Remessa expedida pelo almoxarifado com baixa automática do estoque. A escola deverá confirmar o recebimento no sistema.',
    v_delivery_id,
    jsonb_build_object(
      'document_number', p_document_number,
      'dispatch_date', p_dispatch_date,
      'expedited_by', v_profile.full_name
    )
  );

  return v_delivery_id;
end;
$$;

-- Garante execução das RPCs preservadas após create or replace.
revoke all on function public.save_school_request(uuid, text, text, date, text, text, text, jsonb, boolean)
  from public, anon;
grant execute on function public.save_school_request(uuid, text, text, date, text, text, text, jsonb, boolean)
  to authenticated;

revoke all on function public.authorize_request(uuid, jsonb, text)
  from public, anon;
grant execute on function public.authorize_request(uuid, jsonb, text)
  to authenticated;

revoke all on function public.register_dispatch(uuid, date, text, text, jsonb)
  from public, anon;
grant execute on function public.register_dispatch(uuid, date, text, text, jsonb)
  to authenticated;

commit;
