-- SUPRIR Educação V5.3.1
-- Edição e exclusão de pedidos pela escola antes da autorização da SME.
-- Idempotente e com validação no banco para impedir alterações após a liberação.

begin;

create table if not exists public.request_deletion_audit (
  id bigint generated by default as identity primary key,
  request_id uuid not null,
  protocol_number text,
  school_id uuid references public.schools(id) on delete set null,
  previous_status text not null,
  request_snapshot jsonb not null,
  items_snapshot jsonb not null default '[]'::jsonb,
  deleted_by uuid references auth.users(id) on delete set null,
  deleted_by_name text,
  deleted_by_email text,
  deleted_at timestamptz not null default now()
);

create index if not exists request_deletion_audit_request_idx
  on public.request_deletion_audit (request_id, deleted_at desc);
create index if not exists request_deletion_audit_school_idx
  on public.request_deletion_audit (school_id, deleted_at desc);

alter table public.request_deletion_audit enable row level security;
drop policy if exists request_deletion_audit_admin_select on public.request_deletion_audit;
create policy request_deletion_audit_admin_select
on public.request_deletion_audit for select to authenticated
using (public.is_system_admin(auth.uid()));

revoke all on table public.request_deletion_audit from anon, authenticated;
grant select on table public.request_deletion_audit to authenticated;

create or replace function public.save_school_request(
  p_request_id uuid,
  p_priority text,
  p_purpose text,
  p_requested_delivery_date date,
  p_notes text,
  p_school_contact_name text,
  p_school_contact_phone text,
  p_items jsonb,
  p_submit boolean
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_request public.requests%rowtype;
  v_item record;
  v_material public.materials%rowtype;
  v_request_id uuid;
  v_previous_status text;
begin
  select * into v_profile from public.profiles where id = auth.uid();

  if v_profile.id is null or not v_profile.active or v_profile.account_type <> 'school' or v_profile.school_id is null then
    raise exception 'Seu usuário não está vinculado a uma escola ativa.';
  end if;

  if p_priority not in ('low', 'normal', 'high', 'urgent') then
    raise exception 'Prioridade inválida.';
  end if;

  if nullif(btrim(coalesce(p_purpose, '')), '') is null then
    raise exception 'Informe a finalidade do pedido.';
  end if;

  if p_requested_delivery_date is not null and p_requested_delivery_date < current_date then
    raise exception 'A data desejada não pode ser anterior à data atual.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Adicione pelo menos um material ao pedido.';
  end if;

  if p_request_id is null then
    insert into public.requests (
      school_id, status, priority, purpose, requested_delivery_date, notes,
      school_contact_name, school_contact_phone,
      created_by, created_by_name, created_by_email
    ) values (
      v_profile.school_id, 'draft', p_priority, btrim(p_purpose), p_requested_delivery_date, nullif(btrim(p_notes), ''),
      nullif(btrim(p_school_contact_name), ''), nullif(btrim(p_school_contact_phone), ''),
      auth.uid(), v_profile.full_name, v_profile.email
    ) returning * into v_request;
    v_previous_status := 'draft';
  else
    select * into v_request
    from public.requests
    where id = p_request_id
    for update;

    if v_request.id is null or v_request.school_id <> v_profile.school_id then
      raise exception 'Pedido não encontrado para esta escola.';
    end if;

    if v_request.status not in ('draft', 'submitted', 'under_review') then
      raise exception 'Este pedido já foi liberado ou encerrado e não pode mais ser alterado pela escola.';
    end if;

    v_previous_status := v_request.status;

    update public.requests set
      priority = p_priority,
      purpose = btrim(p_purpose),
      requested_delivery_date = p_requested_delivery_date,
      notes = nullif(btrim(p_notes), ''),
      school_contact_name = nullif(btrim(p_school_contact_name), ''),
      school_contact_phone = nullif(btrim(p_school_contact_phone), '')
    where id = v_request.id
    returning * into v_request;

    delete from public.request_items where request_id = v_request.id;
  end if;

  for v_item in
    select * from jsonb_to_recordset(p_items)
      as x(material_id uuid, quantity numeric, notes text)
  loop
    if v_item.material_id is null or v_item.quantity is null or v_item.quantity <= 0 then
      raise exception 'Existe um item com material ou quantidade inválida.';
    end if;

    select * into v_material
    from public.materials
    where id = v_item.material_id and ativo = true;

    if v_material.id is null then
      raise exception 'Um dos materiais não existe ou está inativo.';
    end if;

    if coalesce(v_material.stock_quantity, 0) <= 0 then
      raise exception 'O material % está sem estoque no momento.', v_material.nome;
    end if;

    if v_item.quantity > v_material.stock_quantity then
      raise exception 'A quantidade solicitada de % ultrapassa o estoque disponível (% %).',
        v_material.nome, v_material.stock_quantity, v_material.unidade;
    end if;

    insert into public.request_items (
      request_id, material_id, requested_quantity, approved_quantity,
      material_name_snapshot, unit_snapshot, school_notes
    ) values (
      v_request.id, v_material.id, v_item.quantity, 0,
      v_material.nome, v_material.unidade, nullif(btrim(v_item.notes), '')
    );
  end loop;

  v_request_id := v_request.id;

  if p_request_id is null then
    if coalesce(p_submit, false) then
      update public.requests set status = 'submitted', submitted_at = now() where id = v_request_id;
      perform public.log_request_event(v_request_id, 'request_submitted', 'draft', 'submitted', 'Pedido enviado pela escola para análise da SME.');
    else
      perform public.log_request_event(v_request_id, 'draft_created', null, 'draft', 'Rascunho do pedido criado pela escola.');
    end if;
  elsif v_previous_status = 'draft' then
    if coalesce(p_submit, false) then
      update public.requests set status = 'submitted', submitted_at = now() where id = v_request_id;
      perform public.log_request_event(v_request_id, 'request_submitted', 'draft', 'submitted', 'Pedido enviado pela escola para análise da SME.');
    else
      perform public.log_request_event(v_request_id, 'draft_updated', 'draft', 'draft', 'Rascunho do pedido atualizado pela escola.');
    end if;
  else
    -- Se o pedido já foi enviado ou recebido pela SME, a edição não retrocede o fluxo.
    -- O status é preservado e a alteração fica registrada no histórico.
    perform public.log_request_event(
      v_request_id,
      'request_updated_by_school',
      v_previous_status,
      v_previous_status,
      'Pedido alterado pela escola antes da autorização da SME.'
    );
  end if;

  return v_request_id;
end;
$$;

create or replace function public.delete_school_request_before_approval(p_request_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_request public.requests%rowtype;
  v_items jsonb;
begin
  select * into v_profile from public.profiles where id = auth.uid();

  if v_profile.id is null or not v_profile.active or v_profile.account_type <> 'school' or v_profile.school_id is null then
    raise exception 'Seu usuário não está vinculado a uma escola ativa.';
  end if;

  select * into v_request
  from public.requests
  where id = p_request_id
  for update;

  if v_request.id is null or v_request.school_id <> v_profile.school_id then
    raise exception 'Pedido não encontrado para esta escola.';
  end if;

  if v_request.status not in ('draft', 'submitted', 'under_review') then
    raise exception 'Este pedido já foi liberado ou encerrado e não pode mais ser excluído pela escola.';
  end if;

  if exists (select 1 from public.deliveries where request_id = p_request_id) then
    raise exception 'Este pedido já possui movimentação de entrega e não pode ser excluído.';
  end if;

  select coalesce(jsonb_agg(to_jsonb(ri) order by ri.created_at), '[]'::jsonb)
  into v_items
  from public.request_items ri
  where ri.request_id = p_request_id;

  insert into public.request_deletion_audit (
    request_id, protocol_number, school_id, previous_status,
    request_snapshot, items_snapshot,
    deleted_by, deleted_by_name, deleted_by_email
  ) values (
    v_request.id, v_request.protocol_number, v_request.school_id, v_request.status,
    to_jsonb(v_request), v_items,
    auth.uid(), v_profile.full_name, v_profile.email
  );

  delete from public.requests where id = p_request_id;
end;
$$;

revoke all on function public.save_school_request(uuid, text, text, date, text, text, text, jsonb, boolean) from public, anon, authenticated;
grant execute on function public.save_school_request(uuid, text, text, date, text, text, text, jsonb, boolean) to authenticated;

revoke all on function public.delete_school_request_before_approval(uuid) from public, anon, authenticated;
grant execute on function public.delete_school_request_before_approval(uuid) to authenticated;

commit;
